[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogen-agentchat",
    "autogen-core",
    "autogen-ext[anthropic]",
    "pypdf",
    "python-docx",
    "openpyxl",
    "python-dotenv"
]
